
name: Pytest

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'mkdocs.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'mkdocs.yml'

# Not possible to test windows capability:
# https://github.com/orgs/community/discussions/25491
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pull swe-agent docker container
        run: docker pull sweagent/swe-agent:latest
      - name: Create keys.cfg
        run: touch keys.cfg
      - name: Install rye
        uses: eifinger/setup-rye@v4
        with:
          version: 'latest'
      - name: Install dependencies
        run: rye sync
      - name: Run replayio tests
        run: rye run replayio-tests
